### ISSUE TITLE
Invalid JSON does not give good error message

### ISSUE THREAD

**Issue by cshunger** [ibm-bluemix-mobile-services/bluemix-generator#28]
When you have invalid JSON in the generator.json file the error message given back is 

error:
 Please navigate to a valid template directory

**Comment by jmeis** [comment]
Thanks Chevy!

We will improve the error message in a future release. I will add this to the backlog.

**Comment by ynunez** [comment]
@cshunger the issue has been addressed. Install the latest version from NPM to get it
