### ISSUE TITLE
cannot get bluegen version number

### ISSUE THREAD

**Issue by cshunger** [ibm-bluemix-mobile-services/bluemix-generator#31]
bluegen -v                                          (*master+47) 12:27:40 
error:
 Please install the Cloud Foundry CLI.
To install, visit and follow the directions from the official https://github.com/cloudfoundry/cli repository.

**Comment by jmeis** [comment]
When you run bluegen on a valid project, it will have the version number on the top. 

Example:

<img width="583" alt="screen shot 2016-09-19 at 5 36 25 pm" src="https://cloud.githubusercontent.com/assets/16617646/18651242/adeb963e-7e8f-11e6-9d5d-1136340b0544.png">

However, I think this would be a good feature. I'm going to label it as an enhancement/feature request.

**Comment by jmeis** [comment]
Added initial non-interactive capability with version flag.

Command:
`bluegen --version`

Will be published with next release.

#39
