### ISSUE TITLE
Support non-interactive generation of patterns

### ISSUE THREAD

**Issue by andrewferrier** [ibm-bluemix-mobile-services/bluemix-generator#38]
Typically, when I'm generating a pattern using `bluegen`, I need to specify certain information, such as my Bluemix ID, org, etc. With the possible exception of my password, which may be trickier to support for security reasons, it would be really nice if there was an automatic way of passing this to a `bluegen` command - perhaps using command-line params. This would save a lot of typing when I'm developing a pattern and repeatedly re-running this. So far I've been automating that with [expect](http://expect.sourceforge.net/) but that's pretty clumsy.

Thanks for your work on `bluegen`, guys - really useful tool!

**Comment by mjperrins** [comment]
@jmeis hey something to look at, might be worth looking at home much work to pass in args on the cli, there will be some kind of arg npm module for this type of stuff

**Comment by jmeis** [comment]
Thanks Andrew!

I think this is a good idea, and I've been investigating this as well for build testing. I'll mark this as an enhancement.

**Comment by ynunez** [comment]
@andrewferrier you can take advantage of the token authentication that only requires you to enter the password the first time you use the tool by creating an environment variable `BLUEGEN_TOKEN_AUTH`and assigning it some non empty string i.e., `true`

https://github.com/ibm-bluemix-mobile-services/bluemix-generator/blob/master/cli.js#L70

For the other things to be non-interactive @jmeis added it to backlog

**Comment by mjperrins** [comment]
@ynunez how is New York :-) keep in touch even if it's through code

**Comment by ynunez** [comment]
@mjperrins I'll be in NY next week but I'm pretty sure it'll be cold 😄

**Comment by jmeis** [comment]
Added initial non-interactive capability:

<img width="488" alt="screen shot 2017-01-12 at 11 16 33 pm" src="https://cloud.githubusercontent.com/assets/16617646/21919081/3620f52a-d91d-11e6-9ad8-a679a7951820.png">

Will be published with next release.

#39
