### ISSUE TITLE
Error: "Please install the Cloud Foundry CLI."

### ISSUE THREAD

**Issue by ericis** [ibm-bluemix-mobile-services/bluemix-generator#43]
Attempting to run `bluegen` results in:
`error: Please install the Cloud Foundry CLI.`

Steps to repro:
1. Install `npm install -g bluemix-generator`
2. Run `bluegen`

**Comment by jmeis** [comment]
Hi Eric,

Thanks for using the **bluemix-generator** tool!

To use bluegen, you must run the command inside a valid template.

Here is an example of a bluegen-compatible template:
https://github.com/ibm-bluemix-mobile-services/backend-for-frontend-node 

If you noticed in the **Before you begin** section, it requires you have the Cloud Foundry CLI installed. You need this CLI installed to deploy your application to Bluemix. To install the Cloud Foundry CLI, follow the directions [here](https://github.com/cloudfoundry/cli).

After installing the necessary pre-requisites, you would essentially go:
1. `git clone https://github.com/ibm-bluemix-mobile-services/backend-for-frontend-node.git`
2. `bluegen`

And then see something like this:

![Bluegen Demo](https://raw.githubusercontent.com/ibm-bluemix-mobile-services/bluemix-generator/master/readme/bluegen.gif)

If this helps, or if you have any more questions, let me know in this issue. For now, I'll close it.
